fix gcl() so it works with an optional directoy specifier

diff --git a/home/shrc b/home/shrc
--- a/home/shrc
+++ b/home/shrc
@@ -869,11 +869,38 @@ gcl()
 {
     if [[ $# -eq 0 ]]
     then
-        echo 'Usage: gcl [git clone args] {basho-repo-name|github-org/repo|git-url}' >&2
+        echo 'Usage: gcl [-b branch] [args --] repo [directory]' >&2
+        echo '  repo: basho-repo-name | github-org/repo | git-url' >&2
         return 1
     fi
     local -a args=("$@")
-    local -i urlx=$((${#args[@]} - 1))
+    local -i argc="${#args[@]}"
+    local -i argx=0 urlx=0
+    while [[ $argx -lt $argc ]]
+    do
+        if [[ "${args[$argx]}" == '--' ]]
+        then
+            let 'urlx = (argx + 1)'
+            break
+        fi
+        let 'argx += 1'
+    done
+    if [[ $urlx -le $argx ]]
+    then
+        if [[ "${args[0]}" == '-b' ]]
+        then
+            argx=2
+        else
+            argx=0
+        fi
+        if [[ "${args[$argx]}" == -* ]]
+        then
+            echo 'Error: non-obvious switch, use -- or invoke directly.' >&2
+            return 1
+        else
+            urlx=$argx
+        fi
+    fi
     local url="${args[$urlx]}"
     case "$url" in
         https:*|ssh:*|git:*|git@*)
